In [1]:
import numpy as np 
import pandas as pd

In [5]:
#load data 
df = pd.read_csv(r"anime.csv")

In [3]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

**make a new column for episode count**

In [6]:
# make a new column for episode count   but we dont have episode count feature ===>so we will do extracting feature
df.loc[2]["Title"]

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [10]:
# create a function to extract episode counts
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt: 
        if i == ")":
             check = False
             return data
    
        if check == True:
            data = data + i 
        if i =="(":
            check = True

In [12]:
df["Episodes"] = df["Title"].apply(extract_episodes)

In [16]:
df["Episodes"] = df["Episodes"].str.replace(" eps", "")
df["Episodes"] = df["Episodes"].astype(int)

In [19]:
# data type of episodes now after conversion from string to int
type(df.loc[5]["Episodes"])

numpy.int64

**Make a new column for timestamp**

In [23]:
df.loc[5]["Title"]

"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members"

In [30]:
# creating a new function for extraction time stamp feature from title 
def time_stamp(txt):
    check = False
    data = ""
    for i in txt:
        if i == ",":
            check = False 
            return data
        if check == True:
            data = data + i
        if i == ")":
            check = True

In [38]:
# better way to do it 
def extract_date(txt):
    check = False
    data= "" 
    for i in range(len(txt)): 
        if txt[i] == ")":
            for j in range(i+1, i+20):
                data += txt[j]
            return data

In [39]:
df["Duration"] = df["Title"].apply(extract_date)

In [44]:
df.head()

,Rank,Title,Score,Episodes,Duration
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [46]:
# Convert duration into start and end dates
dates = df["Duration"].str.split(" - ", expand=True)

start = pd.to_datetime(dates[0], format="%b %Y")
end = pd.to_datetime(dates[1], format="%b %Y")

# Calculate difference in months
df["Months"] = (
    (end.dt.year - start.dt.year) * 12
    + (end.dt.month - start.dt.month)
    + 1
)
df.head()

,Rank,Title,Score,Episodes,Duration,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

**Which anime has the highest score**

In [54]:
df[df["Score"] == df["Score"].max()]

,Rank,Title,Score,Episodes,Duration,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

**Top five highest scoring anime**

In [61]:
df["Score"].value_counts
df[["Title","Score"]].head()

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

**Which enemy has highest episode count?**

In [62]:
df[df["Episodes"] == df["Episodes"].max()]

,Rank,Title,Score,Episodes,Duration,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [63]:
df["Episodes"].max()

201

**Anime with top five episodes count.**

In [70]:
df.nlargest(5,"Episodes")[["Title","Episodes"]]

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7   Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74

**Which anime runs the longest?**

In [72]:
df.nlargest(1, "Months")[["Title", "Episodes", "Months"]]

                                                Title  Episodes  Months
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110     111